# This file was generated by GoReleaser. DO NOT EDIT.
cask "coffee" do
  app "Coffee.app"

  # Quit the running app before an upgrade/uninstall replaces it.
  uninstall quit: "com.jleagle.coffee"

  postflight_steps do
    on_macos do
      # Ad-hoc signed, not notarized — strip the quarantine flag or
      # Gatekeeper blocks the first launch. The `binary` symlink target
      # lives in the staged dir (chdir "."); the app has been moved to
      # the applications dir by this point.
      # ({{appdir}} is a Homebrew runner token, escaped here so
      # GoReleaser's own templating passes it through verbatim.)
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "coffee"], chdir: ".", must_succeed: false
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Coffee.app"], must_succeed: false
      # (Re)launch, so an upgrade restarts the app.
      run "/usr/bin/open", args: ["-a", "{{appdir}}/Coffee.app"], must_succeed: false
    end
  end

  version "0.0.6"

  on_macos do
    sha256 "9fadeb2bb46feeda18b9fb1e5b578077f8572d5c3a9b70f58db98486a89df332"
    url "https://github.com/Jleagle/coffee/releases/download/v#{version}/coffee_#{version}_darwin_all.tar.gz"
  end

  name "coffee"
  desc "Coffee shop CLI and macOS menu bar app"
  homepage "https://github.com/Jleagle/coffee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coffee"

  # No zap stanza required
end
