# This file is regenerated by the release workflow in Jleagle/coffee on every
# tagged release — do not edit the url/sha256 by hand.
#
# Install:
#   brew install Jleagle/coffee/coffee
#   brew services start coffee   # menu bar app, now + at every login
class Coffee < Formula
  desc "Coffee shop CLI and macOS menu bar app"
  homepage "https://github.com/Jleagle/coffee"
  url "https://github.com/Jleagle/coffee/releases/download/v0.1.0/coffee-v0.1.0-macos-universal.tar.gz"
  # Placeholder until the first tagged release publishes real values.
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  depends_on :macos

  def install
    bin.install "coffee"
    libexec.install "coffee-menubar" => "coffee"
  end

  service do
    run [opt_libexec/"coffee"]
    keep_alive true
    log_path var/"log/coffee.log"
    error_log_path var/"log/coffee.log"
  end

  test do
    system bin/"coffee", "--help"
  end
end
